debug: true

spring:
  datasource:
    name: ${postgres_database:monolieta}
    url: jdbc:postgresql://${postgres_hostname:127.0.0.1}/${spring.datasource.name}
    username: ${postgres_user:postgres}
    password: ${postgres_password:postgres}
  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    web: 'DEBUG'