spring:
  main:
    banner-mode: "off"
  messages:
    basename: locale/message
  jpa:
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      location: /var/tmp/monolieta
      max-file-size: 30MB
      max-request-size: 10MB

monolieta:
  app-url: http://localhost:8000
  location: /var/tmp