name: "Main action"
on: push

jobs:
  prepare:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x, 18.x ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: "**/package-lock.json"
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install

  test-assets:
    timeout-minutes: 60
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x, 18.x ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: "**/package-lock.json"
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      - run: npm run test:coverage
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          retention-days: 1
          path: |
            coverage

  test-service:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container: gradle:jdk17-alpine
    env:
      SPRING_PROFILES_ACTIVE: test
      POSTGRES_USER: postgres
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: monolieta
      POSTGRES_PASSWORD: postgres
    services:
      postgres:
        image: postgres:14.2-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - run: |
          apk update
          apk add --no-cache postgresql-client
      - run: |
          sh scripts/create-database.sh
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - run: ./gradlew :monolieta:test
      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: service-reports
          retention-days: 1
          path: |
            services/monolieta/build/reports

  test-e2e:
    timeout-minutes: 60
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x, 18.x ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: "**/package-lock.json"
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      - uses: cypress-io/github-action@v4
        with:
          env: true
          install: false
          start: npx nyc next dev
          wait-on: "http://localhost:3000"
          browser: chrome
      - uses: actions/upload-artifact@v3
        with:
          name: cypress-coverage
          retention-days: 1
          path: |
            cypress-coverage

  test-database:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container: gradle:jdk17-alpine
    services:
      postgres:
        image: postgres:14.2-alpine
        env:
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - run: |
          apk update
          apk add --no-cache postgresql-client
      - run: |
          sh scripts/create-database.sh
          sh scripts/query-database.sh database/structure.sql
        env:
          POSTGRES_USER: postgres
          POSTGRES_HOSTNAME: postgres
          POSTGRES_DATABASE: monolieta

  report-coverage:
    timeout-minutes: 30
    needs: [ "test-assets", "test-e2e" ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x, 18.x ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: "**/package-lock.json"
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/download-artifact@v3
      - run: npm install
      - run: npm run report
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}