name: Validate structure database
on: [push]
jobs:
  postgres:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
  steps:
    - name: Install postgres client
      run: |
        apt-get update
        apt-get install -y postgresql-client-14