name: Validate database
on: push

jobs:
  database:
    runs-on: ubuntu-latest
    container: node:18.1.0-alpine
    services:
      postgres:
        image: postgres:14.2-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
