name: Validate database
on: push

jobs:
  database:
    runs-on: ubuntu-latest
    container: gradle:jdk11-alpine
    services:
      postgres:
        image: postgres:14.2-alpine
        env:
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - run: |
          apk update
          apk add --no-cache postgresql-client
      - run: |
          sh scripts/create-database.sh
        env:
          POSTGRES_HOSTNAME: postgres
          POSTGRES_DATABASE: monolieta
