name: Validate database
on: push

jobs:
  database:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.2-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.16.1"
